
PROGRAM=trjgtk

SOURCE=trj_netcdf.f90 interpol.f90 ptotheta.f90 trj_winds.f90 trj_mod.f90 date_conv.f90 derivs.f90 derivstr.f90 ode.f90 odeint.f90 stereograph.f90 trj_main_mod.f90

CPPSRC=../gui/Gtk-3/TrjApp.cpp

F95=gfortran

FFLAGS=-fdefault-real-8 -fbounds-check
LIBS=-L/usr/lib -lnetcdff
INCLUDES = -I/usr/include

all : $(SOURCE)
	$(F95)  $(FFLAGS) $(INCLUDES) $(SOURCE) $(LIBS) -x c++ $(CPPSRC) -lstdc++ -o $(PROGRAM) `pkg-config gtkmm-3.0 --cflags --libs`
